name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Test SSH Connection
      run: |
        echo "Testing SSH connection..."
        sshpass -p ${{ secrets.SELA_MASTER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SELA_MASTER_USER }}@${{ secrets.SELA_MASTER_IP }} 'echo "SSH Connection successful" && hostname && pwd'

    - name: Test kubectl
      run: |
        echo "Testing kubectl..."
        sshpass -p ${{ secrets.SELA_MASTER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SELA_MASTER_USER }}@${{ secrets.SELA_MASTER_IP }} 'which kubectl && kubectl version --client'

    - name: Create k8s directory on remote
      if: success()
      run: |
        sshpass -p ${{ secrets.SELA_MASTER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SELA_MASTER_USER }}@${{ secrets.SELA_MASTER_IP }} "mkdir -p ~/k8s-deploy"

    - name: Copy k8s files to remote
      if: success()
      run: |
        cd k8s/
        sshpass -p ${{ secrets.SELA_MASTER_PASSWORD }} scp -o StrictHostKeyChecking=no -r * ${{ secrets.SELA_MASTER_USER }}@${{ secrets.SELA_MASTER_IP }}:~/k8s-deploy/

    - name: Deploy to Kubernetes
      if: success()
      run: |
        sshpass -p ${{ secrets.SELA_MASTER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SELA_MASTER_USER }}@${{ secrets.SELA_MASTER_IP }} '
          cd ~/k8s-deploy
          kubectl apply -f .
          kubectl rollout restart deployment flask-app
        '

    - name: Check deployment status
      if: success()
      run: |
        sshpass -p ${{ secrets.SELA_MASTER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SELA_MASTER_USER }}@${{ secrets.SELA_MASTER_IP }} '
          kubectl get pods
          kubectl get services
        '
