name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and test
      run: |
        # Build the image
        docker build -t orelneto/flaskapp_with_db_motogpgif:${{ github.run_number }} .
        
        # Run the application with docker-compose
        docker compose up -d
        
        # Wait for the application to start
        sleep 30
        
        # Test the endpoint
        curl -f http://localhost:5005 || exit 1
        
        # Tag images
        docker tag orelneto/flaskapp_with_db_motogpgif:${{ github.run_number }} orelneto/flaskapp_with_db_motogpgif:latest
        
        # Push images
        docker push orelneto/flaskapp_with_db_motogpgif:${{ github.run_number }}
        docker push orelneto/flaskapp_with_db_motogpgif:latest

    - name: Trigger CD Pipeline
      if: success()
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: trigger-cd
        client-payload: '{"image_tag": "${{ github.run_number }}"}'
